logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: DEBUG
    org.springframework.security: INFO
    fr.codecake.ecom: DEBUG
    org.apache.hc.client5.http: INFO

spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

server:
  port: 8080


application:
  cors:
    allowed-origins:
      - http://localhost:4200
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "*"
    allow-credentials: false
    max-age: 300
