services:
  database:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: 'codecake'
      POSTGRES_PASSWORD: 'codecake'
      POSTGRES_DB: 'codecake'
    ports:
      - '5432:5432'
    volumes:
      - './volumes/codecake-yt/postgres:/var/lib/postgresql/data'
    networks:
      - ecom-network

networks:
  ecom-network:
    driver: bridge 